# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=200)),
                ('foto', models.ImageField(upload_to='foto_autor')),
            ],
        ),
    ]
