# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('chasis', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('anioModelo', models.IntegerField()),
                ('anioCreacion', models.IntegerField()),
                ('produccion', models.CharField(max_length=20)),
                ('motor', models.CharField(max_length=20)),
                ('master', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('observacion', models.TextField()),
            ],
        ),
    ]
