# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descipcion', models.TextField()),
                ('observacion', models.TextField()),
                ('marca', models.CharField(max_length=20)),
            ],
        ),
    ]
