# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloVe',
            fields=[
                ('modelo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descipcion', models.TextField()),
                ('observacion', models.TextField()),
                ('marca', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Modelo',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.ModeloVe'),
        ),
    ]
