# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20160929_1811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModeloVe',
            new_name='Modelo',
        ),
    ]
