# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='marca',
            name='observacion',
            field=models.TextField(blank=True),
        ),
    ]
