# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_auto_20161013_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='id',
        ),
        migrations.AddField(
            model_name='marca',
            name='logo',
            field=models.ImageField(blank=True, upload_to='foto_marca'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='codigo',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
