# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_auto_20161013_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='pais',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
