# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_marca_pais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='modelo',
            new_name='codigo',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='descipcion',
        ),
        migrations.AddField(
            model_name='modelo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='modelo',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Marca'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='observacion',
            field=models.TextField(blank=True),
        ),
    ]
