# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_auto_20161013_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
