# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_auto_20161013_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='tipo_modelo',
            field=models.CharField(default='Toyota', max_length=50),
        ),
    ]
