# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0013_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=50)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[(('AS',), 'AS'), (('ASADF',), 'ASADF'), (('SFSDF',), 'SFSDF')], max_length=20)),
            ],
        ),
    ]
