# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0014_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(choices=[(('Deposito',), 'Deposito'), (('Show Room',), 'Show Room'), (('Taller',), 'Taller'), (('Transito',), 'Transito'), ('Zona Franca', 'Zona Franca')], max_length=20),
        ),
    ]
