# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0015_auto_20161014_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='departamento',
            field=models.CharField(blank=True, choices=[('LPZ', 'La Paz'), ('CBB', 'Cochabamba'), ('SC', 'Santa Cruz'), ('BN', 'Beni'), ('PN', 'Pando'), ('TRJ', 'Tarija'), ('PTS', 'Potosi'), ('TRJ', 'Tarija'), ('SUC', 'Sucre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('DPST', 'Deposito'), ('SWRM', 'Show Room'), ('TLL', 'Taller'), ('TRN', 'Transito'), ('ZF', 'Zona Franca')], max_length=20),
        ),
    ]
